export const types = {
//Auth Actions//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  PLAY_START: 'PLAY_START',
  PLAY_SUCCESS: 'PLAY_SUCCESS',
  PLAY_FAILURE: 'PLAY_FAILURE'
}


export const ERROR = 'error'
