export const types = {
//Auth Actions//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
//User Song Actions
  GET_SONG_START:'GET_SONG_START',
  GET_SONG_SUCCESS: 'GET_SONG_SUCCESS', 
  GET_SONG_FAILURE: 'GET_SONG_FAILURE',
  GET_AUDIO_START: 'GET_AUDIO_START',
  GET_AUDIO_SUCCESS: 'GET_AUDIO_SUCCESS',
  GET_AUDIO_FAILURE: 'GET_AUDIO_FAILURE'
}



export const ERROR = 'error'
